---
- hosts: all

  vars:
  - ove_command: install

  vars_files:
    - ../oah-config.yml

  pre_tasks:
    - include: tasks/init-debian.yml
      when: ansible_os_family == 'Debian'

  roles:
    # Essential roles.
    - oah.oah
    - oah.atom


    # Conditionally-installed roles.

    # Roles for security and stability on production.
